# Generated by Django 5.2.9 on 2025-12-11 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500, verbose_name='Hedef URL')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RUNNING', 'Çalışıyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Başarısız'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=10, verbose_name='Tarama Durumu')),
                ('zap_scan_id', models.IntegerField(blank=True, help_text="ZAP API'den dönen ID. Tarama ilerlemesini izlemek için kullanılır.", null=True, verbose_name='ZAP Aktif Tarama ID')),
                ('scan_type', models.CharField(choices=[('ACTIVE', 'Aktif Tarama'), ('API', 'API Tarama')], default='ACTIVE', max_length=10, verbose_name='Tarama Tipi')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
            ],
            options={
                'verbose_name': 'Tarama İşi',
                'verbose_name_plural': 'Tarama İşleri',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('HIGH', 'Yüksek'), ('MEDIUM', 'Orta'), ('LOW', 'Düşük'), ('INFO', 'Bilgilendirme')], max_length=10, verbose_name='Risk Seviyesi')),
                ('alert_name', models.CharField(max_length=255, verbose_name='Açığın Adı')),
                ('confidence', models.CharField(max_length=50, verbose_name='Güvenilirlik')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Çözüm Önerisi')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Referanslar')),
                ('url', models.URLField(max_length=500, verbose_name="Bulgu URL'si")),
                ('param', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parametre')),
                ('evidence', models.TextField(blank=True, null=True, verbose_name='Kanıt')),
                ('cwe_id', models.IntegerField(blank=True, null=True, verbose_name='CWE ID')),
                ('wasc_id', models.IntegerField(blank=True, null=True, verbose_name='WASC ID')),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='main.scan', verbose_name='Tarama İşi')),
            ],
            options={
                'verbose_name': 'Güvenlik acigi (Alert)',
                'verbose_name_plural': 'Güvenlik Açıkları (Alerts)',
                'ordering': ['risk_level', '-id'],
            },
        ),
    ]
