# Generated by Django 5.2.9 on 2025-12-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scan_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='description',
        ),
    ]
