# Generated by Django 5.2.9 on 2025-12-11 09:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
