# Generated by Django 6.0.5 on 2026-05-15 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('passive', 'Passive'), ('active', 'Active'), ('full', 'Full'), ('api', 'API')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('depth', models.PositiveIntegerField(default=1)),
                ('attack_strength', models.CharField(default='medium', max_length=20)),
                ('use_context', models.BooleanField(default=False)),
                ('proxy_enabled', models.BooleanField(default=False)),
                ('proxy_host', models.CharField(blank=True, max_length=255)),
                ('proxy_port', models.PositiveIntegerField(blank=True, null=True)),
                ('zap_scan_id', models.CharField(blank=True, max_length=64)),
                ('raw_results', models.JSONField(blank=True, default=dict)),
                ('parsed_alerts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZapConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='http://localhost:8080')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zap_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
