# Generated by Django 6.0.5 on 2026-05-15 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='scan',
            name='queue_backend',
            field=models.CharField(default='redis', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('passive', 'Passive'), ('active', 'Active'), ('full', 'Full'), ('api', 'API')], default='passive', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=10)),
                ('custom_interval_minutes', models.PositiveIntegerField(default=60)),
                ('next_run_at', models.DateTimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('queue_backend', models.CharField(default='redis', max_length=20)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedules', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedules', to='targets.target')),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
    ]
